language: objective-c
osx_image: xcode10.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=ValidationToolkit.xcodeproj
  - IOS_FRAMEWORK_SCHEME="ValidationToolkit iOS"
  - OSX_FRAMEWORK_SCHEME="ValidationToolkit macOS"
  - TVOS_FRAMEWORK_SCHEME="ValidationToolkit tvOS"
  - WATCHOS_FRAMEWORK_SCHEME="ValidationToolkit watchOS"
  - IOS_SDK=iphonesimulator
  - MACOS_SDK=macosx
  - TVOS_SDK=appletvsimulator
  - WATCHOS_SDK=watchsimulator
  matrix:
    - DESTINATION="OS=latest,name=iPhone XS"                    SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     CONFIGURATION="Debug" RUN_TESTS="YES" POD_LINT="YES"
    - DESTINATION="arch=x86_64"                                 SCHEME="$OSX_FRAMEWORK_SCHEME"     SDK="$MACOS_SDK"   CONFIGURATION="Debug" RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=latest,name=Apple TV 4K"                  SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    CONFIGURATION="Debug" RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=latest,name=Apple Watch Series 4 - 44mm"  SCHEME="$WATCHOS_FRAMEWORK_SCHEME" SDK="$WATCHOS_SDK" CONFIGURATION="Debug" RUN_TESTS="NO"  POD_LINT="NO"

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - gem install xcpretty --pre --no-document --quiet
  - gem install cocoapods --pre --no-document --quiet
  - echo y | fastlane snapshot reset_simulators --force

script:
  - set -o pipefail
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration "$CONFIGURATION" ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration "$CONFIGURATION" ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi

after_success:
  - if [ $RUN_TESTS == "YES" ]; then
      bash <(curl -s https://codecov.io/bash) -J '^ValidationToolkit$';
    fi
